name: build-docs
on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: planet-viewer/package-lock.json

      - name: Install deps
        working-directory: ./planet-viewer
        run: |
          npm install --no-audit --no-fund

      - name: Angular CLI (local via npx -p npm v11)
        working-directory: ./planet-viewer
        run: |
          npx --yes -p @angular/cli@20 ng version

      - name: Build for Pages into docs/
        working-directory: ./planet-viewer
        run: |
          npx --yes -p @angular/cli@20 ng build --configuration production --output-path ../docs --base-href "/test_jules/"

      - name: Create .nojekyll (empêche GitHub Pages d’ignorer assets)
        run: |
          touch docs/.nojekyll
          echo "/*    /index.html   200" > docs/_redirects || true
          
      - name: SPA fallback (copie 404.html)
        run: cp docs/index.html docs/404.html    

      - name: Commit docs back to main
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "build: update docs for GitHub Pages"
          file_pattern: docs/**
